title:            Xujiajun Blog
description:      Xujiajun'world
url:              https://xujiajun.cn
signoff:          Xujiajun
disqus_shortname: xujiajunblog

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          https://xujiajun.cn
    external:     false
  - name:         Email
    url:          mailto:me@xujiajun.cn
    external:     true
  - name:         GitHub
    url:          http://github.com/xujiajun
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
